### ISSUE TITLE
关键字推送和RSSHUB自建项目支持

### ISSUE THREAD

**Issue by yyy22335** [kylelin1998/RssMonitorTelegramBot#2]
亲爱的开发者，

首先，我要感谢您为这个bot项目所付出的努力和时间。在尝试使用您的bot之后，我觉得有几个方面可能需要改进：

关键字推送: 我个人更倾向于监控某一个关键字，并希望能够得到与该关键字相关的RSS推送。这个功能可以让用户更有针对性地接收信息。

RSSHUB自建项目支持: 在尝试通过RSSHUB自建项目与您的bot进行集成时，我发现似乎不能正确识别。希望您能考虑增加对RSSHUB自建项目的支持。

这些功能对于像我这样的用户将会非常有用。谢谢您考虑我的建议，期待您的回应。

**Comment by kylelin1998** [comment]
关键词匹配才推送这个功能这两天就会开发。

RSSHUB上有哪些不能正确识别呢？ 可以举例下吗？ 具体的不能识别到底是怎样的一种情况呢？ 如果有图的话可以贴出来

**Comment by yyy22335** [comment]
> 关键词匹配才推送这个功能这两天就会开发。
> 
> RSSHUB上有哪些不能正确识别呢？ 可以举例下吗？ 具体的不能识别到底是怎样的一种情况呢？ 如果有图的话可以贴出来

具体来说，那就是https://rsshub.app/telegram/channel/hostlocpreview 这样的url，bot能正确识别，但是如果是自建的rsshub项目例如地址：https://xx.app/telegram/channel/hostlocpreview 就会提示：仅支持RSS XML格式, 请再次将RSS的新URL发送给我

**Comment by kylelin1998** [comment]
听你描述看起来像是部署后本身并不能访问导致的问题， 你有尝试访问过自己部署后的网址吗， 能正确返回XML格式吗

**Comment by yyy22335** [comment]
是的，因为其他rss软件都能正常工作，而我通过网页访问A地址和B地址，看起来是一样的。

**Comment by kylelin1998** [comment]
机器人是部署国内还是国外服务器？
RSSHUB是部署在国内还是国外？

**Comment by yyy22335** [comment]
都是部署在国外的，是只有我一个人遇到这个问题了么

**Comment by kylelin1998** [comment]
目前看来是的， 因为我一个朋友也是自建的RSSHUB， 正常工作

方便贴出你的A、B地址私聊发给我吗？ 或者录个视频看看， 主要想看下两个地址访问后的一个情况

**Comment by kylelin1998** [comment]
已更新版本至1.0.75， 支持包含关键词 和 SSL证书自定义关闭
此两项设置已解决你上述的两个问题， 在机器人里面使用 /admin 命令进行升级， 设置
